/**
 * Build-time content generation script.
 * Reads markdown files and generates a TypeScript module with HTML content.
 *
 * Usage: bun scripts/build-content.ts
 */

import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'fs';
import { resolve, dirname } from 'path';
import { markdownToHtml } from './markdown.js';

const ROOT = resolve(dirname(import.meta.path), '..', '..');
const OUT_DIR = resolve(dirname(import.meta.path), '..', 'src', 'generated');

// Route mapping: file path (relative to project root) → content key
const routeMap: Array<[string, string]> = [
  ['README.md', 'home'],
  ['docs/getting-started.md', 'getting-started'],
  ['docs/api/README.md', 'api'],
  ['docs/api/test-runner.md', 'api/test-runner'],
  ['docs/api/assertions.md', 'api/assertions'],
  ['docs/api/dom.md', 'api/dom'],
  ['docs/api/mocking.md', 'api/mocking'],
  ['docs/README.md', 'docs'],
  ['docs/architecture.md', 'architecture'],
  ['docs/developer/README.md', 'developer'],
  ['docs/developer/setup.md', 'developer/setup'],
  ['docs/developer/testing.md', 'developer/testing'],
  ['docs/developer/building.md', 'developer/building'],
  ['docs/developer/releasing.md', 'developer/releasing'],
  ['docs/user/README.md', 'user'],
  ['docs/user/installation.md', 'user/installation'],
  ['docs/user/configuration.md', 'user/configuration'],
];

function extractTitle(markdown: string): string {
  const match = markdown.match(/^#\s+(.+)/m);
  return match ? match[1].trim() : 'Untitled';
}

function stripReadmeHeader(markdown: string): string {
  // Remove markdownlint-disable comment and the logo/image header from README.md
  let result = markdown;
  // Remove <!-- markdownlint-disable ... --> lines
  result = result.replace(/<!--\s*markdownlint-disable[^>]*-->\s*/g, '');
  // Remove the <img> logo tag and surrounding whitespace
  result = result.replace(/<img[^>]*\/?\s*>\s*/g, '');
  // Remove <br clear="both" /> tags
  result = result.replace(/<br[^>]*\/?\s*>\s*/g, '');
  return result.trim();
}

function main() {
  if (!existsSync(OUT_DIR)) {
    mkdirSync(OUT_DIR, { recursive: true });
  }

  const entries: Record<string, { title: string; html: string }> = {};

  for (const [filePath, key] of routeMap) {
    const fullPath = resolve(ROOT, filePath);
    if (!existsSync(fullPath)) {
      console.warn(`Warning: ${filePath} not found, skipping.`);
      continue;
    }

    let markdown = readFileSync(fullPath, 'utf-8');

    // Strip header from root README
    if (key === 'home') {
      markdown = stripReadmeHeader(markdown);
    }

    const title = extractTitle(markdown);
    const html = markdownToHtml(markdown);

    entries[key] = { title, html };
    console.log(`  ${key}: "${title}" (${html.length} bytes)`);
  }

  // Generate TypeScript module
  const tsContent = `// Auto-generated by scripts/build-content.ts — do not edit manually.
export const content: Record<string, { title: string; html: string }> = ${JSON.stringify(entries, null, 2)};
`;

  const outPath = resolve(OUT_DIR, 'content.ts');
  writeFileSync(outPath, tsContent, 'utf-8');

  // Also write pure JSON for vite.config.ts noscript plugin consumption
  const jsonPath = resolve(OUT_DIR, 'content.json');
  writeFileSync(jsonPath, JSON.stringify(entries, null, 2), 'utf-8');

  console.log(`\nGenerated ${outPath} with ${Object.keys(entries).length} pages.`);
}

main();
